{{- if .Values.orderService.enabled -}}
# Service for Order Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "store-app.fullname" . }}-{{ .Values.orderService.service.name }}
  labels:
    {{- include "store-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
spec:
  type: {{ .Values.orderService.service.type }}
  ports:
    - port: {{ .Values.orderService.service.port }}
      targetPort: {{ .Values.orderService.service.port }}
      name: http
  selector:
    {{- include "store-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
---
# Deployment for Order Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "store-app.fullname" . }}-order-service
  labels:
    {{- include "store-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: order-service
spec:
  replicas: {{ .Values.orderService.replicaCount }}
  selector:
    matchLabels:
      {{- include "store-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: order-service
  template:
    metadata:
      labels:
        {{- include "store-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: order-service
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "store-app.serviceAccountName" . }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: order-service
          image: "{{ .Values.orderService.image.repository }}:{{ .Values.orderService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.orderService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.orderService.service.port }}
          env:
            - name: ORDER_QUEUE_HOSTNAME
              value: {{ printf "%s-%s" (include "store-app.fullname" .) .Values.rabbitmq.service.name | quote }}
            - name: ORDER_QUEUE_PORT
              value: {{ .Values.rabbitmq.service.amqpPort | quote }}
            - name: ORDER_QUEUE_USERNAME
              value: {{ .Values.rabbitmq.credentials.username | quote }}
            - name: ORDER_QUEUE_PASSWORD
              value: {{ .Values.rabbitmq.credentials.password | quote }}
            - name: ORDER_QUEUE_NAME
              value: {{ .Values.orderService.env.queueName | quote }}
            - name: FASTIFY_ADDRESS
              value: {{ .Values.orderService.env.fastifyAddress | quote }}
          resources:
            {{- toYaml .Values.orderService.resources | nindent 12 }}
          {{- with .Values.orderService.probes.startup }}
          startupProbe:
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            failureThreshold: {{ .failureThreshold }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
          {{- end }}
          {{- with .Values.orderService.probes.readiness }}
          readinessProbe:
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            failureThreshold: {{ .failureThreshold }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
          {{- end }}
          {{- with .Values.orderService.probes.liveness }}
          livenessProbe:
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            failureThreshold: {{ .failureThreshold }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
          {{- end }}
      {{- if and .Values.rabbitmq.enabled .Values.orderService.initContainers.waitForRabbitmq.enabled }}
      initContainers:
        - name: wait-for-rabbitmq
          image: {{ .Values.orderService.initContainers.waitForRabbitmq.image }}
          command: {{ .Values.orderService.initContainers.waitForRabbitmq.command | toYaml | nindent 10 | replace "{{ .Release.Name }}-rabbitmq" (printf "%s-rabbitmq" (include "store-app.fullname" .)) | replace "{{ .Values.rabbitmq.service.amqpPort }}" (.Values.rabbitmq.service.amqpPort | toString) }}
          resources:
            {{- toYaml .Values.orderService.initContainers.waitForRabbitmq.resources | nindent 12 }}
      {{- end }}
{{- end }}
