{{- if .Values.productService.enabled -}}
apiVersion: {{ include "store-app.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "store-app.fullname" . }}-product-service
  labels:
    {{- include "store-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: product-service
spec:
  replicas: {{ .Values.productService.replicaCount }}
  selector:
    matchLabels:
      {{- include "store-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: product-service
  template:
    metadata:
      labels:
        {{- include "store-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: product-service
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "store-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: product-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.productService.image.repository }}:{{ .Values.productService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.productService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.productService.service.port }}
              protocol: TCP
          env:
            - name: AI_SERVICE_URL
              value: {{ .Values.productService.env.aiServiceUrl | quote }}
          resources:
            {{- toYaml .Values.productService.resources | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.productService.probes.readiness | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.productService.probes.liveness | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    {{- include "store-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: product-service
spec:
  type: {{ .Values.productService.service.type }}
  ports:
    - port: {{ .Values.productService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "store-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: product-service
{{- end }}
