apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: store
  namespace: demo-app 
spec:
  interval: 15m
  chart:
    spec:
      chart: ./helm/store-app
      sourceRef:
        kind: GitRepository
        name: aks-store-ops 
        namespace: flux-system
  values:
    rabbitmq:
      image:
        repository: mcr.microsoft.com/mirror/docker/library/rabbitmq
        tag: "3.10-management-alpine"
    orderService:
      image:
        repository: ghcr.io/azure-samples/aks-store-demo/order-service
        tag: latest
    productService:
      image:
        repository: ghcr.io/azure-samples/aks-store-demo/product-service
        tag: latest
    storeFront:
      image:
        repository: ghcr.io/azure-samples/aks-store-demo/store-front
        tag: latest
