name: Update Application Image Tag

on:
  repository_dispatch:
    types: [new-image] # This event type will be triggered by the app's CI pipeline

jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ops repository
        uses: actions/checkout@v4
        with:
          # This token is necessary to push changes back to the repository
          token: ${{ secrets.PAT_FOR_OPS_REPO }} # Create this PAT in your aks-store-ops repo secrets

      - name: Update image tag in HelmRelease
        run: |
          echo "Received image tag: ${{ github.event.client_payload.image_tag }}"
          if [ -z "${{ github.event.client_payload.image_tag }}" ]; then
            echo "Error: No image_tag provided in the dispatch payload."
            exit 1
          fi
          
          # Install yq for safer YAML manipulation
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
          
          # Update the image tag in app-release.yaml
          # Ensure this path is correct for your app-release.yaml
          yq e '.spec.values.image.tag = "${{ github.event.client_payload.image_tag }}"' -i deploy/aks/foundation/aks-store-demo/app-release.yaml
          
          echo "Updated app-release.yaml content:"
          cat deploy/aks/foundation/aks-store-demo/app-release.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add deploy/aks/foundation/aks-store-demo/app-release.yaml
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update application image tag to ${{ github.event.client_payload.image_tag }} via CI"
            git push
          fi
